import React, { useEffect, useState } from 'react';
import { usePartnerStore } from '../../../store/partnerStore';
import { Eye, Wallet } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';

const PartnerPayoutList = () => {
    const navigate = useNavigate();
    const { payoutsData, payoutsLoading, fetchPayouts } = usePartnerStore();
    const [page, setPage] = useState(1);
    const limit = 20;

    useEffect(() => {
        fetchPayouts({ skip: (page - 1) * limit, limit });
    }, [page, fetchPayouts]);

    const totalPaid = payoutsData?.payouts?.filter(p => p.status === 'disbursed').reduce((acc, p) => acc + p.net_payable, 0) || 0;

    return (
        <div className="animate-fade-in relative">
            <div className="page-header" style={{ marginBottom: '24px' }}>
                <h1 className="page-title">Payout History</h1>
            </div>

            <div className="card stat-card" style={{ padding: '24px', marginBottom: '24px', maxWidth: '300px' }}>
                <div className="stat-card-title">Total Paid from Statements</div>
                <div className="stat-card-value" style={{ color: 'var(--accent-green)', display: 'flex', alignItems: 'center', gap: '12px' }}>
                    ₹{totalPaid.toLocaleString('en-IN')}
                    <Wallet size={24} style={{ opacity: 0.5 }} />
                </div>
            </div>

            <div className="card" style={{ padding: '24px' }}>
                <h3 style={{ fontSize: '1.2rem', fontWeight: 600, marginBottom: '24px' }}>All Statements</h3>

                <div className="table-container">
                    <table className="premium-table">
                        <thead>
                            <tr>
                                <th>Statement ID</th>
                                <th>Period</th>
                                <th>Net Payable</th>
                                <th>Status</th>
                                <th>Disbursed At</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {payoutsLoading ? (
                                Array.from({ length: 5 }).map((_, i) => (
                                    <tr key={i}>
                                        <td><div className="skeleton skeleton-text" style={{ width: '80%' }}></div></td>
                                        <td><div className="skeleton skeleton-text" style={{ width: '80%' }}></div></td>
                                        <td><div className="skeleton skeleton-text" style={{ width: '80%' }}></div></td>
                                        <td><div className="skeleton skeleton-text" style={{ width: '80%' }}></div></td>
                                        <td><div className="skeleton skeleton-text" style={{ width: '80%' }}></div></td>
                                        <td><div className="skeleton skeleton-text" style={{ width: '60px', height: '30px' }}></div></td>
                                    </tr>
                                ))
                            ) : payoutsData?.payouts?.length === 0 ? (
                                <tr>
                                    <td colSpan="6" style={{ textAlign: 'center', padding: '48px', color: 'var(--text-muted)' }}>
                                        <div style={{ fontSize: '1.2rem', marginBottom: '8px', color: 'var(--text-primary)', fontWeight: 600 }}>No payout statements found.</div>
                                        Statements will appear here when generated by an administrator.
                                    </td>
                                </tr>
                            ) : (
                                payoutsData?.payouts?.map(p => (
                                    <tr key={p.statement_id}>
                                        <td style={{ fontFamily: 'monospace' }}>{p.statement_id.substring(0, 8)}</td>
                                        <td style={{ fontWeight: 500 }}>
                                            {new Date(p.period_start).toLocaleDateString(undefined, { month: 'short', year: 'numeric' })} – {new Date(p.period_end).toLocaleDateString(undefined, { month: 'short', year: 'numeric' })}
                                        </td>
                                        <td style={{ fontWeight: 600, color: 'var(--primary)' }}>₹{p.net_payable.toLocaleString('en-IN')}</td>
                                        <td>
                                            {(() => {
                                                let badgeType = 'yellow';
                                                if (p.status === 'finalized') badgeType = 'blue';
                                                else if (p.status === 'disbursed') badgeType = 'green';
                                                return <span className={`status-badge badge-${badgeType}`}>{p.status}</span>;
                                            })()}
                                        </td>
                                        <td>{p.disbursed_at ? new Date(p.disbursed_at).toLocaleDateString() : '—'}</td>
                                        <td>
                                            <button className="premium-btn premium-btn-secondary" style={{ padding: '6px 12px', fontSize: '0.8rem', display: 'flex', alignItems: 'center', gap: '6px' }} onClick={() => navigate(`/partner/payouts/${p.statement_id}`)}>
                                                <Eye size={14} /> View
                                            </button>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>

                {/* Pagination Controls */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '24px', paddingTop: '16px', borderTop: '1px solid var(--border-color)' }}>
                    <div style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
                        Showing {payoutsData?.payouts?.length ? ((page - 1) * limit) + 1 : 0}–{Math.min(page * limit, payoutsData?.total || 0)}
                    </div>
                    <div style={{ display: 'flex', gap: '8px' }}>
                        <button className="premium-btn premium-btn-secondary" disabled={page === 1} onClick={() => setPage(p => p - 1)}>
                            Previous
                        </button>
                        <button className="premium-btn premium-btn-secondary" disabled={!payoutsData?.payouts || payoutsData.payouts.length < limit} onClick={() => setPage(p => p + 1)}>
                            Next
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default PartnerPayoutList;
